services:
  obb_detector:
    container_name: obb_detector
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - 8081
    ports:
      - "8081:8081"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
    - my_network
networks:
  my_network:
    driver: bridge
